language: python
sudo: required #temporary
dist: trusty

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - libopenblas-dev
      - liblapack-dev
      - gfortran
      - cmake
      - cmake-data
      - swig
      - libav-tools
      - libboost-all-dev
      - libjpeg-dev
      - zlib1g-dev
      - python-dev

install:
  #dependeicies via pip
  - travis_wait pip install -r requirements.txt
  - travis_wait pip install nose nose-parameterized
  # intalling AgentNet
  - pip install .
  # installing Gym
  - git clone https://github.com/openai/gym.git
  - cd gym && pip install -e . && cd ..
  - cd gym && pip install -e '.[atari]' && cd ..
  - cd gym && pip install -e '.[classic_control]' && cd ..

script:
  - nosetests tests --verbose --nocapture  --failure-detail
