language: python
sudo: required

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - libblas-dev
      - liblapack-dev
      - cmake
      - cmake-data
      - python-dev
      - python3-dev
      - python-numpy
      - swig
      - libav-tools
      - libboost-all-dev
      - libjpeg-dev
      - zlib1g-dev
      - gfortran
      - g++-5

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION
  - travis_retry conda install --yes pip numpy scipy six pandas nomkl
  - travis_retry conda install --yes theano scikit-learn nose matplotlib
  - pip install -r requirements.txt
  - pip install .
  - git clone https://github.com/openai/gym.git
  - cd gym && pip install -e '.[all]' && cd ..

script:
  - nosetests tests
